# MSDS458 - Week 2 Discussion Post
X-OR Neural Network<br>
Below I try two approaches to the XOR problem: using raw Python code and with TensorFlow

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
tf.__version__

'2.1.0'

# Raw Python Code
Source: https://towardsdatascience.com/perceptrons-logical-functions-and-the-xor-problem-37ca5025790a

Defining necessary functions:

In [3]:
def unit_step(v):
    #Heavyside Step function. v must be a scalar
    if v >= 0:
        return 1
    else:
        return 0

def perceptron(x, w, b):
    #Function implemented by a perceptron with weight vector w and bias b
    v = np.dot(w, x) + b
    y = unit_step(v)
    return y

def NOT_percep(x):
    w = -1
    b = 0.5
    return perceptron(x, w, b)

def AND_percep(x):
    w = np.array([1, 1])
    b = -1.5
    return perceptron(x, w, b)

def OR_percep(x):
    w = np.array([1, 1])
    b = -0.5
    return perceptron(x, w, b)

def XOR_percep(x):
    gate_1 = AND_percep(x)
    gate_2 = NOT_percep(gate_1)
    gate_3 = OR_percep(x)
    new_x = np.array([gate_2, gate_3])
    output = AND_percep(new_x)
    return output

Defining Test arrays:

In [4]:
example1 = np.array([1, 1])
example2 = np.array([1, 0])
example3 = np.array([0, 1])
example4 = np.array([0, 0])

Testing:

In [13]:
print("AND({}, {}) = {}".format(1, 1, AND_percep(example1)))
print("AND({}, {}) = {}".format(1, 0, AND_percep(example2)))
print("AND({}, {}) = {}".format(0, 1, AND_percep(example3)))
print("AND({}, {}) = {}".format(0, 0, AND_percep(example4)))
print("-------------")
print("OR({}, {}) = {}".format(1, 1, OR_percep(example1)))
print("OR({}, {}) = {}".format(1, 0, OR_percep(example2)))
print("OR({}, {}) = {}".format(0, 1, OR_percep(example3)))
print("OR({}, {}) = {}".format(0, 0, OR_percep(example4)))
print("-------------")
print("XOR({}, {}) = {}".format(1, 1, XOR_percep(example1)))
print("XOR({}, {}) = {}".format(1, 0, XOR_percep(example2)))
print("XOR({}, {}) = {}".format(0, 1, XOR_percep(example3)))
print("XOR({}, {}) = {}".format(0, 0, XOR_percep(example4)))

AND(1, 1) = 1
AND(1, 0) = 0
AND(0, 1) = 0
AND(0, 0) = 0
-------------
OR(1, 1) = 1
OR(1, 0) = 1
OR(0, 1) = 1
OR(0, 0) = 0
-------------
XOR(1, 1) = 0
XOR(1, 0) = 1
XOR(0, 1) = 1
XOR(0, 0) = 0


# Using TensorFlow
Source: https://github.com/marjoleinspronk/XORproblem/blob/master/XOR_TensorFlow2.0.ipynb

Creating data sets:

In [5]:
x_train, y_train = (tf.constant([[0,0],[0,1],[1,0],[1,1]], "float32"), tf.constant([[0],[1],[1],[0]], "float32"))

Creating Neural Network model:

In [22]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(2,)),
  tf.keras.layers.Dense(2, activation=tf.nn.relu),   # hidden layer
  tf.keras.layers.Dense(1, activation=tf.nn.sigmoid)   # output layer
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

Fitting model:

In [23]:
model.fit(x_train, y_train, epochs=1000)

Train on 4 samples
Epoch 1/1000
4/4 [==============================] - 0s 107ms/sample - loss: 0.6395 - accuracy: 0.7500
Epoch 2/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.6391 - accuracy: 0.7500
Epoch 3/1000
4/4 [==============================] - 0s 526us/sample - loss: 0.6388 - accuracy: 0.7500
Epoch 4/1000
4/4 [==============================] - 0s 526us/sample - loss: 0.6384 - accuracy: 0.7500
Epoch 5/1000
4/4 [==============================] - 0s 501us/sample - loss: 0.6380 - accuracy: 0.7500
Epoch 6/1000
4/4 [==============================] - 0s 557us/sample - loss: 0.6376 - accuracy: 0.7500
Epoch 7/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.6372 - accuracy: 0.7500
Epoch 8/1000
4/4 [==============================] - 0s 358us/sample - loss: 0.6368 - accuracy: 0.7500
Epoch 9/1000
4/4 [==============================] - 0s 386us/sample - loss: 0.6364 - accuracy: 0.7500
Epoch 10/1000
4/4 [==============================] - 0s 497us/s

Epoch 81/1000
4/4 [==============================] - 0s 343us/sample - loss: 0.6101 - accuracy: 0.7500
Epoch 82/1000
4/4 [==============================] - 0s 508us/sample - loss: 0.6098 - accuracy: 0.7500
Epoch 83/1000
4/4 [==============================] - 0s 249us/sample - loss: 0.6095 - accuracy: 0.7500
Epoch 84/1000
4/4 [==============================] - 0s 283us/sample - loss: 0.6092 - accuracy: 0.7500
Epoch 85/1000
4/4 [==============================] - 0s 446us/sample - loss: 0.6089 - accuracy: 0.7500
Epoch 86/1000
4/4 [==============================] - 0s 506us/sample - loss: 0.6085 - accuracy: 0.7500
Epoch 87/1000
4/4 [==============================] - 0s 376us/sample - loss: 0.6082 - accuracy: 0.7500
Epoch 88/1000
4/4 [==============================] - 0s 516us/sample - loss: 0.6078 - accuracy: 0.7500
Epoch 89/1000
4/4 [==============================] - 0s 257us/sample - loss: 0.6075 - accuracy: 0.7500
Epoch 90/1000
4/4 [==============================] - 0s 751us/sample - lo

Epoch 160/1000
4/4 [==============================] - 0s 308us/sample - loss: 0.5874 - accuracy: 1.0000
Epoch 161/1000
4/4 [==============================] - 0s 257us/sample - loss: 0.5871 - accuracy: 1.0000
Epoch 162/1000
4/4 [==============================] - 0s 250us/sample - loss: 0.5868 - accuracy: 1.0000
Epoch 163/1000
4/4 [==============================] - 0s 540us/sample - loss: 0.5865 - accuracy: 1.0000
Epoch 164/1000
4/4 [==============================] - 0s 803us/sample - loss: 0.5863 - accuracy: 1.0000
Epoch 165/1000
4/4 [==============================] - 0s 506us/sample - loss: 0.5860 - accuracy: 1.0000
Epoch 166/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5857 - accuracy: 1.0000
Epoch 167/1000
4/4 [==============================] - 0s 250us/sample - loss: 0.5854 - accuracy: 1.0000
Epoch 168/1000
4/4 [==============================] - 0s 250us/sample - loss: 0.5851 - accuracy: 1.0000
Epoch 169/1000
4/4 [==============================] - 0s 492us/s

Epoch 239/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5632 - accuracy: 1.0000
Epoch 240/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5628 - accuracy: 1.0000
Epoch 241/1000
4/4 [==============================] - 0s 509us/sample - loss: 0.5625 - accuracy: 1.0000
Epoch 242/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5622 - accuracy: 1.0000
Epoch 243/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5618 - accuracy: 1.0000
Epoch 244/1000
4/4 [==============================] - 0s 498us/sample - loss: 0.5615 - accuracy: 1.0000
Epoch 245/1000
4/4 [==============================] - 0s 540us/sample - loss: 0.5612 - accuracy: 1.0000
Epoch 246/1000
4/4 [==============================] - 0s 770us/sample - loss: 0.5609 - accuracy: 1.0000
Epoch 247/1000
4/4 [==============================] - 0s 319us/sample - loss: 0.5605 - accuracy: 1.0000
Epoch 248/1000
4/4 [==============================] - 0s 504us/s

Epoch 318/1000
4/4 [==============================] - 0s 508us/sample - loss: 0.5367 - accuracy: 1.0000
Epoch 319/1000
4/4 [==============================] - 0s 680us/sample - loss: 0.5364 - accuracy: 1.0000
Epoch 320/1000
4/4 [==============================] - 0s 529us/sample - loss: 0.5360 - accuracy: 1.0000
Epoch 321/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5357 - accuracy: 1.0000
Epoch 322/1000
4/4 [==============================] - 0s 520us/sample - loss: 0.5354 - accuracy: 1.0000
Epoch 323/1000
4/4 [==============================] - 0s 353us/sample - loss: 0.5350 - accuracy: 1.0000
Epoch 324/1000
4/4 [==============================] - 0s 257us/sample - loss: 0.5347 - accuracy: 1.0000
Epoch 325/1000
4/4 [==============================] - 0s 269us/sample - loss: 0.5343 - accuracy: 1.0000
Epoch 326/1000
4/4 [==============================] - 0s 555us/sample - loss: 0.5340 - accuracy: 1.0000
Epoch 327/1000
4/4 [==============================] - 0s 257us/s

Epoch 397/1000
4/4 [==============================] - 0s 525us/sample - loss: 0.5087 - accuracy: 1.0000
Epoch 398/1000
4/4 [==============================] - 0s 345us/sample - loss: 0.5084 - accuracy: 1.0000
Epoch 399/1000
4/4 [==============================] - 0s 249us/sample - loss: 0.5080 - accuracy: 1.0000
Epoch 400/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5076 - accuracy: 1.0000
Epoch 401/1000
4/4 [==============================] - 0s 537us/sample - loss: 0.5073 - accuracy: 1.0000
Epoch 402/1000
4/4 [==============================] - 0s 512us/sample - loss: 0.5069 - accuracy: 1.0000
Epoch 403/1000
4/4 [==============================] - 0s 312us/sample - loss: 0.5067 - accuracy: 1.0000
Epoch 404/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.5063 - accuracy: 1.0000
Epoch 405/1000
4/4 [==============================] - 0s 252us/sample - loss: 0.5059 - accuracy: 1.0000
Epoch 406/1000
4/4 [==============================] - 0s 498us/s

Epoch 476/1000
4/4 [==============================] - 0s 498us/sample - loss: 0.4804 - accuracy: 1.0000
Epoch 477/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.4801 - accuracy: 1.0000
Epoch 478/1000
4/4 [==============================] - 0s 719us/sample - loss: 0.4797 - accuracy: 1.0000
Epoch 479/1000
4/4 [==============================] - 0s 249us/sample - loss: 0.4794 - accuracy: 1.0000
Epoch 480/1000
4/4 [==============================] - 0s 581us/sample - loss: 0.4790 - accuracy: 1.0000
Epoch 481/1000
4/4 [==============================] - 0s 260us/sample - loss: 0.4786 - accuracy: 1.0000
Epoch 482/1000
4/4 [==============================] - 0s 261us/sample - loss: 0.4782 - accuracy: 1.0000
Epoch 483/1000
4/4 [==============================] - 0s 256us/sample - loss: 0.4779 - accuracy: 1.0000
Epoch 484/1000
4/4 [==============================] - 0s 329us/sample - loss: 0.4776 - accuracy: 1.0000
Epoch 485/1000
4/4 [==============================] - 0s 889us/s

Epoch 555/1000
4/4 [==============================] - 0s 249us/sample - loss: 0.4517 - accuracy: 1.0000
Epoch 556/1000
4/4 [==============================] - 0s 506us/sample - loss: 0.4514 - accuracy: 1.0000
Epoch 557/1000
4/4 [==============================] - 0s 492us/sample - loss: 0.4510 - accuracy: 1.0000
Epoch 558/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.4507 - accuracy: 1.0000
Epoch 559/1000
4/4 [==============================] - 0s 249us/sample - loss: 0.4503 - accuracy: 1.0000
Epoch 560/1000
4/4 [==============================] - 0s 538us/sample - loss: 0.4499 - accuracy: 1.0000
Epoch 561/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.4496 - accuracy: 1.0000
Epoch 562/1000
4/4 [==============================] - 0s 250us/sample - loss: 0.4492 - accuracy: 1.0000
Epoch 563/1000
4/4 [==============================] - 0s 323us/sample - loss: 0.4488 - accuracy: 1.0000
Epoch 564/1000
4/4 [==============================] - 0s 499us/s

Epoch 634/1000
4/4 [==============================] - 0s 457us/sample - loss: 0.4232 - accuracy: 1.0000
Epoch 635/1000
4/4 [==============================] - 0s 507us/sample - loss: 0.4228 - accuracy: 1.0000
Epoch 636/1000
4/4 [==============================] - 0s 558us/sample - loss: 0.4224 - accuracy: 1.0000
Epoch 637/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.4221 - accuracy: 1.0000
Epoch 638/1000
4/4 [==============================] - 0s 508us/sample - loss: 0.4217 - accuracy: 1.0000
Epoch 639/1000
4/4 [==============================] - 0s 349us/sample - loss: 0.4214 - accuracy: 1.0000
Epoch 640/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.4210 - accuracy: 1.0000
Epoch 641/1000
4/4 [==============================] - 0s 666us/sample - loss: 0.4206 - accuracy: 1.0000
Epoch 642/1000
4/4 [==============================] - 0s 252us/sample - loss: 0.4203 - accuracy: 1.0000
Epoch 643/1000
4/4 [==============================] - 0s 499us/s

Epoch 713/1000
4/4 [==============================] - 0s 749us/sample - loss: 0.3950 - accuracy: 1.0000
Epoch 714/1000
4/4 [==============================] - 0s 305us/sample - loss: 0.3946 - accuracy: 1.0000
Epoch 715/1000
4/4 [==============================] - 0s 251us/sample - loss: 0.3943 - accuracy: 1.0000
Epoch 716/1000
4/4 [==============================] - 0s 249us/sample - loss: 0.3940 - accuracy: 1.0000
Epoch 717/1000
4/4 [==============================] - 0s 429us/sample - loss: 0.3936 - accuracy: 1.0000
Epoch 718/1000
4/4 [==============================] - 0s 368us/sample - loss: 0.3932 - accuracy: 1.0000
Epoch 719/1000
4/4 [==============================] - 0s 591us/sample - loss: 0.3928 - accuracy: 1.0000
Epoch 720/1000
4/4 [==============================] - 0s 558us/sample - loss: 0.3925 - accuracy: 1.0000
Epoch 721/1000
4/4 [==============================] - 0s 255us/sample - loss: 0.3921 - accuracy: 1.0000
Epoch 722/1000
4/4 [==============================] - 0s 249us/s

Epoch 792/1000
4/4 [==============================] - 0s 760us/sample - loss: 0.3675 - accuracy: 1.0000
Epoch 793/1000
4/4 [==============================] - 0s 506us/sample - loss: 0.3672 - accuracy: 1.0000
Epoch 794/1000
4/4 [==============================] - 0s 551us/sample - loss: 0.3668 - accuracy: 1.0000
Epoch 795/1000
4/4 [==============================] - 0s 325us/sample - loss: 0.3665 - accuracy: 1.0000
Epoch 796/1000
4/4 [==============================] - 0s 268us/sample - loss: 0.3661 - accuracy: 1.0000
Epoch 797/1000
4/4 [==============================] - 0s 783us/sample - loss: 0.3658 - accuracy: 1.0000
Epoch 798/1000
4/4 [==============================] - 0s 512us/sample - loss: 0.3655 - accuracy: 1.0000
Epoch 799/1000
4/4 [==============================] - 0s 250us/sample - loss: 0.3651 - accuracy: 1.0000
Epoch 800/1000
4/4 [==============================] - 0s 261us/sample - loss: 0.3647 - accuracy: 1.0000
Epoch 801/1000
4/4 [==============================] - 0s 755us/s

Epoch 871/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.3410 - accuracy: 1.0000
Epoch 872/1000
4/4 [==============================] - 0s 530us/sample - loss: 0.3407 - accuracy: 1.0000
Epoch 873/1000
4/4 [==============================] - 0s 506us/sample - loss: 0.3404 - accuracy: 1.0000
Epoch 874/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.3401 - accuracy: 1.0000
Epoch 875/1000
4/4 [==============================] - 0s 336us/sample - loss: 0.3398 - accuracy: 1.0000
Epoch 876/1000
4/4 [==============================] - 0s 543us/sample - loss: 0.3394 - accuracy: 1.0000
Epoch 877/1000
4/4 [==============================] - 0s 275us/sample - loss: 0.3391 - accuracy: 1.0000
Epoch 878/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.3388 - accuracy: 1.0000
Epoch 879/1000
4/4 [==============================] - 0s 814us/sample - loss: 0.3384 - accuracy: 1.0000
Epoch 880/1000
4/4 [==============================] - 0s 595us/s

Epoch 950/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.3159 - accuracy: 1.0000
Epoch 951/1000
4/4 [==============================] - 0s 506us/sample - loss: 0.3156 - accuracy: 1.0000
Epoch 952/1000
4/4 [==============================] - 0s 273us/sample - loss: 0.3153 - accuracy: 1.0000
Epoch 953/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.3150 - accuracy: 1.0000
Epoch 954/1000
4/4 [==============================] - 0s 704us/sample - loss: 0.3147 - accuracy: 1.0000
Epoch 955/1000
4/4 [==============================] - 0s 531us/sample - loss: 0.3144 - accuracy: 1.0000
Epoch 956/1000
4/4 [==============================] - 0s 558us/sample - loss: 0.3140 - accuracy: 1.0000
Epoch 957/1000
4/4 [==============================] - 0s 499us/sample - loss: 0.3137 - accuracy: 1.0000
Epoch 958/1000
4/4 [==============================] - 0s 542us/sample - loss: 0.3134 - accuracy: 1.0000
Epoch 959/1000
4/4 [==============================] - 0s 529us/s

Results:

In [41]:
predictions = model.predict(x_train).round()
for item in range(4):
    print(x_train[item], " = ", predictions[item])
#print(x_train[0])
#print(model.predict(x_train).round())  

tf.Tensor([0. 0.], shape=(2,), dtype=float32)  =  [0.]
tf.Tensor([0. 1.], shape=(2,), dtype=float32)  =  [1.]
tf.Tensor([1. 0.], shape=(2,), dtype=float32)  =  [1.]
tf.Tensor([1. 1.], shape=(2,), dtype=float32)  =  [0.]


Checking Weights:

In [24]:
model.trainable_variables

[<tf.Variable 'dense_2/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 1.4236846, -1.1323034],
        [-1.4239069,  1.1321944]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32, numpy=array([-0.00024844, -0.00039478], dtype=float32)>,
 <tf.Variable 'dense_3/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[1.6542103],
        [1.7018974]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(1,) dtype=float32, numpy=array([-0.8762149], dtype=float32)>]